# Generated by Django 4.2.10 on 2024-02-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientEntity',
        ),
    ]
